### ISSUE TITLE
Undefined class constant 'ZipArchive::EM_NONE'

### ISSUE THREAD

**Issue by lookitsjonno** [comodojo/zip#8]
After upgrade to php 7.2 I get

Error - Undefined class constant 'ZipArchive::EM_NONE' in DOCROOT/fuel/vendor/comodojo/zip/src/Comodojo/Zip/Zip.php on line 77

Version 3 installed with

Zip version | 1.15.4
Libzip version | 1.1.2

**Comment by marcogiovinazzi** [comment]
The issue seems to be related to the version of libzip. PHP 7.2 supports the [selection of zip encryption methods only if compiled against libzip ≥ 1.2.0](https://www.php.net/manual/en/ziparchive.setencryptionname.php) and the 3.x branch of comodojo/zip has a [strict dependency on that functionality](https://github.com/comodojo/zip/blob/3.0/src/Comodojo/Zip/Interfaces/ZipInterface.php#L40).

There is no easy solution, but I see two options:
1. switch back to comodojo/zip 2.x, that does not support the creation of encrypted zip files
2. upgrade your PHP/libzip to a newer version ([PHP 7.2](https://www.php.net/supported-versions.php) is out of active support since 30 Nov 2019 and will receive security updates until 30 Nov 2020). The next version of the 3.x branch of comodojo/zip will have the min-php flag set to 7.3. 

I hope this can help solving your issue.

**Comment by cord** [comment]
my app is running on ths environment

https://phpinfo-74.frb.io

with zlib 1.2.11 (seems to be the latest version).

Any idea?

**Comment by marcogiovinazzi** [comment]
According to the [PHP documentation](https://www.php.net/manual/en/ziparchive.setencryptionname.php):

> Note:
> This function is only available if built against libzip ≥ 1.2.0.

It looks like you have **1.1.2** (zlib is not used by this lib).

**Comment by cord** [comment]
thanks for the clarification - was reading too fast. we check with the hoster to update libzip

**Comment by cord** [comment]
fortrabbit won't upgrade for now - is there a workaround? 

I see the missing constant is set as default in `/comodojo/zip/src/Comodojo/Zip/Zip.php:204` but cant see how I could use that in my code

`$addZip = $manager->addZip(\Comodojo\Zip\Zip::open($ZipFileA))->addZip(\Comodojo\Zip\Zip::open($ZipFileB));`

where I add Zip archives.

**Comment by marcogiovinazzi** [comment]
@cord I'm afraid there is no easy workaround, that constant is used by the lib to determine and set the right encryption mode.

If you have no option to upgrade you libzip, you can consider using _comodojo/zip ^2.1_, that has the same APIs but no extra functionalities (ref. CHANGELOG.md). In that case please be aware that there is no plan to release additional versions based on the 2.X branch (i.e. 2.1.1 is the last one) and you'll be using pretty old code (Aug 2017).
